apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: court-management
data:
  APP_NAME: "Court Management"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://localhost"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "court_management"
  DB_USERNAME: "court_user"
