apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: court-management
type: Opaque
stringData:
  APP_KEY: "base64:URs8bo53c8QKaybzdr9RnJM4cgvuVTUDfG7b99mu9/8="
  DB_PASSWORD: "secret"
